[project]
name = "dataengineering"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "notebook>=7.4.4",
    "numpy>=2.3.2",
    "pillow>=11.3.0",
    "tifffile>=2025.6.11",
    "tiffile>=2018.10.18",
]
